services:
  app:
    build: .
    container_name: advanced-task-manager
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: >
      bash -c "
              composer install &&
              while ! nc -z database 3306; do
                echo 'Waiting for database to be ready...'
                sleep 1
              done &&
              php bin/console doctrine:database:create --if-not-exists &&
              php bin/console doctrine:migrations:migrate --no-interaction &&
              php bin/console app:seed-tasks --no-interaction &&
              apache2-foreground"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:symfony@database:3306/symfony
    depends_on:
      database:
        condition: service_started
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: advanced-task-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
